// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package greeter

// Injectors from wire.go:

func Initialize() (Greeter, error) {
	useCase := NewUseCase()
	greeterGreeter := NewGreeter(useCase)
	return greeterGreeter, nil
}
